Bundle "nono/vim-handlebars"
Bundle "leshill/vim-json"
Bundle "tpope/vim-bundler"
Bundle 'ervandew/supertab'
Bundle "kien/rainbow_parentheses.vim"
Bundle "delimitMate.vim"
Bundle 'tpope/vim-rake'
Bundle 'flazz/vim-colorschemes'
Bundle 'pangloss/vim-javascript'
Bundle 'mxw/vim-jsx'
Bundle 'elixir-lang/vim-elixir'
Bundle 'jimenezrick/vimerl'
