if [ -d $HOME/.bashrc.d ]; then
  for conf in $HOME/.bashrc.d/*.bsh; do
    . $conf
  done
fi

source $HOME/.profile

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/workmad3/.lmstudio/bin"
# End of LM Studio CLI section

