#!/bin/bash

pushd $(dirname "$0")
current_dir=$(pwd)
popd

curl -Lo install.sh https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
sh install.sh --unattended
rm install.sh

if [[ "$OSTYPE" == "darwin"* ]]; then
echo "/usr/local/bin/zsh" >> /etc/shells
fi

ln -fs $current_dir/profile $HOME/.profile
ln -fs $current_dir/profile.d $HOME/.profile.d
ln -fs $current_dir/zshrc $HOME/.zshrc
ln -fs $current_dir/zsh_profile $HOME/.zsh_profile
ln -fs $current_dir/zsh.aliases $HOME/.zsh.aliases
ln -fs $current_dir/oh-my-zsh/themes/workmad3.zsh-theme $HOME/.oh-my-zsh/themes/workmad3.zsh-theme
ln -fs $current_dir/zshrc.d $HOME/.zshrc.d
ln -fs $current_dir/zsh-completions.d $HOME/.zsh-completions.d
ln -fs $current_dir/zsh-commands.d $HOME/.zsh-commands.d

ln -fs $current_dir/bashrc $HOME/.bashrc
ln -fs $current_dir/bash_profile $HOME/.bash_profile
ln -fs $current_dir/bashrc.d $HOME/.bashrc.d
ln -fs $current_dir/op-accounts $HOME/.op-accounts
